
const weatherMapping = {
    "Sunny": "Clear",
    "Clear": "Clear",
    "Patchy rain possible": "Light Rain",
    "Patchy snow possible": "Light Snow",
    "Patchy sleet possible": "Light Sleet",
    "Patchy freezing drizzle possible": "Light Freezing Drizzle",
    "Thundery outbreaks possible": "Thunderstorms",
    "Blowing snow": "Blowing Snow",
    "Blizzard": "Blizzard",
    "Fog": "Fog",
    "Freezing fog": "Freezing Fog",
    "Patchy light drizzle": "Light Drizzle",
    "Light drizzle": "Light Drizzle",
    "Freezing drizzle": "Freezing Drizzle",
    "Heavy freezing drizzle": "Heavy Freezing Drizzle",
    "Patchy light rain": "Light Rain",
    "Light rain": "Light Rain",
    "Moderate rain at times": "Moderate Rain",
    "Heavy rain at times": "Heavy Rain",
    "Heavy rain": "Heavy Rain",
    "Light freezing rain": "Light Freezing Rain",
    "Moderate or heavy freezing rain": "Freezing Rain",
    "Light sleet": "Light Sleet",
    "Moderate or heavy sleet": "Sleet",
    "Patchy light snow": "Light Snow",
    "Light snow": "Light Snow",
    "Patchy moderate snow": "Moderate Snow",
    "Moderate snow": "Moderate Snow",
    "Patchy heavy snow": "Heavy Snow",
    "Heavy snow": "Heavy Snow",
    "Ice pellets": "Ice Pellets",
    "Light rain shower": "Light Rain Showers",
    "Moderate or heavy rain shower": "Rain Showers",
    "Torrential rain shower": "Torrential Rain Showers",
    "Light sleet showers": "Light Sleet Showers",
    "Moderate or heavy sleet showers": "Sleet Showers",
    "Light snow showers": "Light Snow Showers",
    "Moderate or heavy snow showers": "Snow Showers",
    "Light showers of ice pellets": "Light Showers of Ice Pellets",
    "Moderate or heavy showers of ice pellets": "Showers of Ice Pellets",
    "Patchy light rain with thunder": "Light Rain with Thunder",
    "Moderate or heavy rain with thunder": "Rain with Thunder",
    "Patchy light snow with thunder": "Light Snow with Thunder",
    "Moderate or heavy snow with thunder": "Snow with Thunder",
};

export function SimplifiedWeatherCondition(inputString) {
    // return weatherMapping[inputString] || inputString;
    return inputString;
}