
const weatherMapping = {
    "Blizzard": "Blizzard",
    "Blowing snow": "snowy-3.svg",
    "Clear": "clear-day.svg",
    "Clear day": "clear-day.svg",
    "Cloudy": "cloudy.svg",
    "Fog": "fog.svg",
    "Freezing fog": "Freezing Fog",
    "Freezing drizzle": "Freezing Drizzle",
    "Heavy Freezing Drizzle": "Heavy Freezing Drizzle",
    "Heavy Rain": "rainy-3.svg",
    "Heavy snow": "snowy-3.svg",
    "Ice Pellets": "Ice Pellets",
    "Light Drizzle": "Light Drizzle",
    "Light Freezing Drizzle": "Light Freezing Drizzle",
    "Light Freezing Rain": "rain-and-sleet-mix.svg",
    "Light freezing rain": "rain-and-sleet-mix.svg",
    "Light rain shower": "rainy-1-day.svg",
    "Light rain": "rainy-1-day.svg",
    "Light Rain with Thunder": "Light Rain with Thunder",
    "Light Showers of Ice Pellets": "Light Showers of Ice Pellets",
    "Light Sleet": "rain-and-sleet-mix.svg",
    "Light Sleet Showers": "rain-and-sleet-mix.svg",
    "Light sleet showers": "rain-and-sleet-mix.svg",
    "Light Snow": "snowy-1.svg",
    "Light snow showers": "snowy-1.svg",
    "Mist": "fog.svg",
    "Moderate rain": "rainy-1.svg",
    "Moderate Snow": "snowy-2.svg",
    "Overcast": "cloudy.svg",
    "Partly cloudy": "cloudy-1-day.svg",
    "Patchy freezing drizzle possible": "Light Freezing Drizzle",
    "Patchy heavy snow": "Heavy Snow",
    "Patchy light drizzle": "Light Drizzle",
    "Patchy light rain": "rainy-1.svg",
    "Patchy light rain with thunder": "Light Rain with Thunder",
    "Patchy light snow": "snowy-1.svg",
    "Patchy light snow with thunder": "Light Snow with Thunder",
    "Patchy rain possible": "rainy-1-day.svg",
    "Patchy sleet possible": "Light Sleet",
    "Patchy snow possible": "snowy-1-day.svg",
    "Rain Showers": "Rain Showers",
    "Rain with Thunder": "Rain with Thunder",
    "Showers of Ice Pellets": "Showers of Ice Pellets",
    "Sleet": "Sleet",
    "Sleet Showers": "Sleet Showers",
    "Snow Showers": "Snow Showers",
    "Snow with Thunder": "Snow with Thunder",
    "Sunny": "clear-day.svg",
    "Thundery outbreaks possible": "thunderstorms.svg",
    "Torrential Rain Showers": "Torrential Rain Showers",
  };
    

export function TextToImg(inputString) {
    return weatherMapping[inputString] || inputString;
}