
const weatherMappingNight = {
    "Blizzard": "Blizzard",
    "Blowing snow": "snowy-3.svg",
    "Clear": "clear-night.svg",
    "Clear day": "clear-day.svg",
    "Cloudy": "cloudy-1-night.svg",
    "Fog": "fog-night.svg",
    "Freezing fog": "Freezing Fog",
    "Freezing drizzle": "Freezing Drizzle",
    "Heavy Freezing Drizzle": "Heavy Freezing Drizzle",
    "Heavy rain": "rainy-3-night.svg",
    "Heavy snow": "snowy-3-night.svg",
    "Ice Pellets": "Ice Pellets",
    "Light drizzle": "rainy-1-night.svg",
    "Light Freezing Drizzle": "Light Freezing Drizzle",
    "Light Freezing Rain": "rain-and-sleet-mix.svg",
    "Light freezing rain": "rain-and-sleet-mix.svg",
    "Light rain shower": "rainy-1-night.svg",
    "Light rain": "rainy-1-night.svg",
    "Light Rain with Thunder": "Light Rain with Thunder",
    "Light Showers of Ice Pellets": "Light Showers of Ice Pellets",
    "Light Sleet": "rain-and-sleet-mix.svg",
    "Light Sleet Showers": "rain-and-sleet-mix.svg",
    "Light sleet showers": "rain-and-sleet-mix.svg",    
    "Light snow": "snowy-1-night.svg",
    "Light snow showers": "snowy-1-night.svg",
    "Mist": "fog.svg",
    "Moderate rain": "rainy-1-night.svg",
    "Moderate rain at times": "rainy-1-night.svg",
    "Moderate Snow": "snowy-2-night.svg",
    "Moderate or heavy rain with thunder": "isolated-thunderstorms-night.svg",
    "Moderate or heavy snow showers": "isolated-thunderstorms.svg",
    "Overcast": "cloudy.svg",
    "Partly cloudy": "cloudy-1-night.svg",
    "Patchy freezing drizzle possible": "Light Freezing Drizzle",
    "Patchy moderate snow": "rain-and-snow-mix.svg",
    "Patchy heavy snow": "Heavy Snow",
    "Patchy light drizzle": "rainy-2-night.svg",
    "Patchy light rain": "rainy-1-night.svg",
    "Patchy light rain with thunder": "Light Rain with Thunder",
    "Patchy light snow": "snowy-1-night.svg",
    "Patchy light rain with thunder": "scattered-thunderstorms-night.svg",
    "Patchy light snow with thunder": "Light Snow with Thunder",
    "Patchy rain possible": "rainy-1-night.svg",
    "Patchy sleet possible": "Light Sleet",
    "Patchy snow possible": "snowy-1-night.svg",
    "Rain Showers": "Rain Showers",
    "Rain with Thunder": "Rain with Thunder",
    "Showers of Ice Pellets": "Showers of Ice Pellets",
    "Sleet": "Sleet",
    "Sleet Showers": "Sleet Showers",
    "Snow Showers": "Snow Showers",
    "Snow with Thunder": "Snow with Thunder",
    "Sunny": "clear-night.svg",
    "Thundery outbreaks possible": "thunderstorms.svg",
    "Torrential Rain Showers": "Torrential Rain Showers",
  };
    


const weatherMappingDay = {
  "Blizzard": "Blizzard",
  "Blowing snow": "snowy-3.svg",
  "Clear": "clear-day.svg",
  "Clear day": "clear-day.svg",
  "Cloudy": "cloudy.svg",
  "Fog": "fog.svg",
  "Freezing fog": "Freezing Fog",
  "Freezing drizzle": "Freezing Drizzle",
  "Heavy Freezing Drizzle": "Heavy Freezing Drizzle",
  "Heavy rain": "rainy-3.svg",
  "Heavy snow": "snowy-3.svg",
  "Ice Pellets": "Ice Pellets",
  "Light drizzle": "rainy-1.svg",
  "Light Freezing Drizzle": "Light Freezing Drizzle",
  "Light Freezing Rain": "rain-and-sleet-mix.svg",
  "Light freezing rain": "rain-and-sleet-mix.svg",
  "Light rain shower": "rainy-1-day.svg",
  "Light rain": "rainy-1-day.svg",
  "Light Rain with Thunder": "Light Rain with Thunder",
  "Light Showers of Ice Pellets": "Light Showers of Ice Pellets",
  "Light Sleet": "rain-and-sleet-mix.svg",
  "Light Sleet Showers": "rain-and-sleet-mix.svg",
  "Light sleet showers": "rain-and-sleet-mix.svg",    
  "Light snow": "snowy-1.svg",
  "Light snow showers": "snowy-1.svg",
  "Mist": "fog.svg",
  "Moderate rain": "rainy-1.svg",
  "Moderate rain at times": "rainy-1.svg",
  "Moderate Snow": "snowy-2.svg",
  "Moderate or heavy rain with thunder": "isolated-thunderstorms.svg",
  "Moderate or heavy snow showers": "isolated-thunderstorms.svg",
  "Overcast": "cloudy.svg",
  "Partly cloudy": "cloudy-1-day.svg",
  "Patchy freezing drizzle possible": "Light Freezing Drizzle",
  "Patchy moderate snow": "rain-and-snow-mix.svg",
  "Patchy heavy snow": "Heavy Snow",
  "Patchy light drizzle": "rainy-2-night.svg",
  "Patchy light rain": "rainy-1.svg",
  "Patchy light rain with thunder": "Light Rain with Thunder",
  "Patchy light snow": "snowy-1.svg",
  "Patchy light rain with thunder": "scattered-thunderstorms.svg",
  "Patchy light snow with thunder": "Light Snow with Thunder",
  "Patchy rain possible": "rainy-1-day.svg",
  "Patchy sleet possible": "Light Sleet",
  "Patchy snow possible": "snowy-1-day.svg",
  "Rain Showers": "Rain Showers",
  "Rain with Thunder": "Rain with Thunder",
  "Showers of Ice Pellets": "Showers of Ice Pellets",
  "Sleet": "Sleet",
  "Sleet Showers": "Sleet Showers",
  "Snow Showers": "Snow Showers",
  "Snow with Thunder": "Snow with Thunder",
  "Sunny": "clear-day.svg",
  "Thundery outbreaks possible": "thunderstorms.svg",
  "Torrential Rain Showers": "Torrential Rain Showers",
};
  

export function TextToImg(inputString, isDay = null) {
  if(isDay){
    return weatherMappingDay[inputString] || inputString;

  }
  else
    return weatherMappingNight[inputString] || inputString;

}